/**
 * Mock token data for testing and demo purposes
 */

export const MOCK_TOKENS = [
  {
    id: 1,
    symbol: "WETH",
    name: "Wrapped Ether",
    amount: 1.5,
    price: 2500,
    priceChange: 2.3,
    usdValue: 3750,
  },
  {
    id: 2,
    symbol: "WBTC",
    name: "Wrapped Bitcoin",
    amount: 0.1,
    price: 45000,
    priceChange: -1.2,
    usdValue: 4500,
  },
  {
    id: 3,
    symbol: "SOL",
    name: "Wrapped Solana",
    amount: 0.015,
    price: 3.5,
    priceChange: -0.5,
    usdValue: 0.05,
  },
  {
    id: 4,
    symbol: "BNB",
    name: "Binance Coin",
    amount: 2.5,
    price: 320,
    priceChange: 1.8,
    usdValue: 800,
  },
  {
    id: 5,
    symbol: "stETH",
    name: "Lido Staked Ether",
    amount: 0.8,
    price: 2480,
    priceChange: 2.1,
    usdValue: 1984,
  },
  {
    id: 6,
    symbol: "LINK",
    name: "Chainlink",
    amount: 0.12,
    price: 0.45,
    priceChange: -2.3,
    usdValue: 0.054,
  },
  {
    id: 7,
    symbol: "USDC",
    name: "USD Coin",
    amount: 500,
    price: 1.0,
    priceChange: 0.1,
    usdValue: 500,
  },
  {
    id: 8,
    symbol: "USDT",
    name: "Tether USD",
    amount: 0.075,
    price: 1.0,
    priceChange: 0.0,
    usdValue: 0.075,
  },
];
